[package]
name = "search-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="dynamic_indexing"
path="src/dynamic_indexing.rs"

[dependencies]
